alarms/alarm_manager.py, alarms/slack_alarm.py
use 'encounter_id' instead of 'id' to avoid duplicate notification.
=> fix duplicate notification

alarms.json.default, alarms/pushbullet_alarm.py
If the user fills the channel field in alarms.json, the script will attempt to push to that channel instead of pushing to all the devices of the given account.
=> Implement pushing to Pushbullet channel

README.md
Just changed the things I noticed while reading through the README.md
=> Fixed some typos and references to the new PokemonGo-Map Repo

README.md, alarms.json.default, alarms/alarm_manager.py, alarms/pushover_alarm.py, alarms/slack_alarm.py
Added support for the pushover.net push-messaging service for Android & iOS and wanted to share it.
=> Added Support for Pushover.net Service

alarms/geofence.py, requirements.txt
The geofence option didn't work for me. Locations that were inside the geofence didn't trigger an alarm. 
In my implementation I use the SymPy.geomery library to do the calculation if a location is inside or outside the geofence. Two options are implemented to specify a geofence using 2 or more coordinated. When 2 are given a rectangle is created, otherwise a polygon is made.
Tested it on my own Ubuntu 14.04 system and using Docker. It is running for a day already.
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] My code follows the code style of this project.
=> Fix Geofence

alarms/alarm_manager.py
Fixed the spelling of "implemented"
No testing required for spelling errors.
No wiki update required
- [ x] My code follows the code style of this project.
I noticed these spelling mistakes while running in debug mode :).
=> Spelling Fixes

alarms.json.default, alarms/Pushbullet/pushbullet_alarm.py, alarms/Pushover/pushover_alarm.py, alarms/Slack/slack_alarm.py, alarms/Telegram/telegram_alarm.py, alarms/Twilio/twilio_alarm.py
Applied the startup message switch from #140  to the other services. And also include them in the alarms.json.example
On my own system.
=> Startup message for other services

.gitignore, alarms/Pushbullet/pushbullet_alarm.py, alarms/Pushover/pushover_alarm.py, alarms/Slack/slack_alarm.py, alarms/Telegram/telegram_alarm.py, alarms/Twilio/twilio_alarm.py, alarms/Twitter/twitter_alarm.py, alarms/alarm_manager.py, alarms/utils.py
Added an option to output a list of all pokemon that are being monitored on all services.  This list is sorted by the Pokemon's Poke ID #.  It also outputs the same message to the console.
Slack, Telegram and the Console will also output the distance alert setting for each individual pokemon in parenthesis after each Pokemon name.  Pokemon whose distance is set to "True" will display (Unl) for unlimited distance. 
Need to add to each services page this option:
startup_list - Display list of pokemon monitored upon startup in (service name) service
- For Twilio I implemented a sleep between messages, to help ensure that text messages are delivered in order.  The sleep value may need to be adjusted after testing on different carriers.
=> Added startup_list message to all services

alarms/Boxcar/boxcar_alarm.py
=> Fix POST parameter for notification sound.

setup.py
Adds a setup file, which enables other projects to use PokeAlarm via "-e git+git://github.com/kvangent/PokeAlarm#egg=pokealarm" in their requirements.txt file.
With pip.
Not needed.
=> Added setup file

alarms.json.default, alarms/FacebookPages/__init__.py, alarms/FacebookPages/facebookpages_alarm.py, alarms/alarm_manager.py
These `alarms.json` parameters - `active`, `type`, and `page_access_token` - are required to enable the Facebook Pages alarm service:
| Parameters         | Description                            |
| --------------     |----------------------------------------|
| type               | must be `facebookpages`                |
| active             | `True` for alarm to be active          |
| page_access_token  | Your permanent FB page access token    |
```json
{
"active": "True",
"type":"facebookpages",
"page_access_token":"YOUR_PAGE_ACCESS_TOKEN"
}
```
**Note:** The above code is to be inserted into the alarms section of alarms.json. It does not represent the entire alarms.json file.
In addition to the 3 required parameters, several optional parameters are available to personalize your …
=> Facebook Pages Support

Dockerfile, requirements.txt
Added missing Dockerfile for v3 and updated requirement.txt as pytz was required to run v3 in a docker container
Docker image created on my own server using this PR.
Have 4 instances of PokeAlarm currently running based on this docker images.
None
=> Added Docker Support

locales/it/teams.json
I'm trying to fix one by one all the italian locales files.
These are the correct translation for this file.
Team Name in Italian are different.
It's tested on my Linux Server. It's only a translation.
No Wiki Update needed
=> Update teams.json in Italian locales

PokeAlarm/Manager.py, PokeAlarm/WebhookStructs.py
Use \<height\>, \<weight\>, \<gender\>
Haven't add the options to filter height, weight, and genders
Tested, working good.
=> Add Height, Weight, Gender

PokeAlarm/Utils.py
The DIR expansion currently only shows NE/NW/SE/SW, and never pure cardinal directions (N, S, E, W). This enables all 8 possible directions.
Tested in real-life Twitter feed.
=> Enable pure cardinal directions (N, S, E, W) in addition to NE/NW/SE/SW.

locales/move_info.json
Update move_info.json
My own computer
=> Update move info

PokeAlarm/FacebookPage/FacebookPageAlarm.py
Add options to change attachment (link) caption, description, image and name
Tested in my installation, full backwards compatible.
Will update Facebook wiki page after this is considered for merging
=> Improve Facebook integration

PokeAlarm/Manager.py, PokeAlarm/Telegram/Stickers.py, PokeAlarm/Telegram/TelegramAlarm.py
Changed how tg stickers are chosen, before they used the translated team names, which caused stickers not to get send, when using a language other then English.
Tested with various gym changes in a test telegram channel, generated by REST client.
Don't think there is a need for a change in wiki, because it's just a bugfix.
=> Fix team sticker when using a language other then english.

PokeAlarm/Filters.py, PokeAlarm/Manager.py, PokeAlarm/WebhookStructs.py, filters.json.example
Adds CP functionality and the ``<cp>`` DTS for it.
On a custom setup with this clean PR pull.
=> CP - Dynamic Text Substitution 

PokeAlarm/Filters.py, PokeAlarm/Manager.py, PokeAlarm/WebhookStructs.py
Adds level functionality for incoming RM pr# 1911 and the <level> DTS for it.
On a custom setup with this clean PR pull.
=> Level dynamic text replace

PokeAlarm/WebhookStructs.py
Added <tiny_rat> and <big_karp> dts that returns an empty string unless its a big karp or tiny rat in which case it returns "big" or "tiny"
Working on my setup
=> Add tiny_rat and big_karp dts

filters.json.example
I had thought of putting some of the ones that can leave besides Articuno and Lugia that they leave currently but I think that it is better to put all the present legendary ones and soon they will be retouched if there is some change
in my local PokeAlarm
=> Add legendary pokes in filters example

PokeAlarm/Telegram/TelegramAlarm.py
Fixed stickers for gym changes in Telegram
Tested with different Gym changes on local machine
=> Fix TG Gym sticker

PokeAlarm/Manager.py
Allow emitting the unown form letter with the "form" tag
Tested with monocle with unown form webhook support patch (https://github.com/Noctem/Monocle/pull/284)
- [X ] New feature (non-breaking change which adds functionality)
- [ X] My code follows the code style of this project.
- [ X] My change requires a change to the documentation.
=> Added support for unown form name

README.md
Update the PokeAlarm readme for the RocketMap discord
No need, just a readme change 😉
=> Update readme for Rocketmap discord

.github/ISSUE_TEMPLATE.md, Dockerfile, README.md, license.txt, start_pokealarm.py
Fixed incorrect link of patch notes in readme and update old PokemonGo-Map references to RocketMap
Missed to update this reference
=> fix wrong link and update references

README.md
The patch notes hyperlink still does not work and now I put the complete url to make it work properly definitively
=>  Fix patch notes hyperlink again

PokeAlarm/Manager.py
The Team Name information on Raids can be very helpful.  A previous commit had team name in both eggs and raids but it disappeared and when added back only added back to Raids.  My commit adds the same change to Eggs as well. 
Yes, on my own instance sending to my discord server
=> Adding <team_id> and <team_name> to raid egg notifications

PokeAlarm/WebhookStructs.py
Add one option for pokemon, pokestop, gym, egg and raid: 
<lat_5>: Latitude rounded to 5 decimals
<lng_5>: Longitude rounded to 5 decimals
Only five-digit accuracy of coordinates will be sent to discord, telegram and so on.
Sometimes it is more convenient to send a link with coordinates through messages. The default latitude/longitude is too long, while only 5 decimals are accurate enough to locate it.
Tested on my Discord server and Telegram.
=> Add one option for coordinates accuracy

PokeAlarm/Manager.py
A log message refers to a Raid when it was meant for an Egg.
Correct log messages help finding bugs ;)
Local map
=> Egg/Raid Typo

README.md
Fix urls in README, show the hidden donate shield and fix again the patch notes url #424 
Fix urls
Local repo
=> Fix urls in README

filters.json.example
Correct the name of Victreebel raid in filters.example
Incorrect name of raid boss
Change incorrect name with official name, same name in pokemon section
=> Fix Victreebel raid boss name in filters.example.json

config/config.ini.example, start_pokealarm.py
The help text for the new cache_type configuration has a cut/paste error which errantly mentions the google API.  This corrects that as well as making it clear that there are two choices, mem or file.
Help text should be correct
=> Correct incorrect cache help description

tools/webhook_test.py
Fixes issue with location not getting set
Also a few minor fixes
Will fix #483
A lot of people have geofences set up with their PA, and without location settings being fixed the webhook tester will always show as outside of geofence
Tested locally by using it
=> Webhook Tester Location Fix

.travis.yml
Adds continuous integration testing via TravisCI.
=> TravisCI style checking.

PokeAlarm/Alarms/Discord/__init__.py, PokeAlarm/Alarms/FacebookPage/__init__.py, PokeAlarm/Alarms/Pushbullet/__init__.py, PokeAlarm/Alarms/Slack/__init__.py, PokeAlarm/Alarms/Telegram/__init__.py, PokeAlarm/Alarms/Twilio/__init__.py
Fixes lazy loading
It tries to use imports before they are actually loaded, so move the use of the lazily-loaded import to below when it is loaded
Poorly, only tested using webhook tester and Discord
=> Fix lazy loading

PokeAlarm/Events/Egg.py, PokeAlarm/Events/Event.py, PokeAlarm/Events/Gym.py, PokeAlarm/Events/Monster.py, PokeAlarm/Events/Raid.py, PokeAlarm/Events/Stop.py, PokeAlarm/Events/__init__.py, PokeAlarm/WebhookStructs/RocketMap.py, PokeAlarm/__init__.py
This PR is the start of how Events are handled in PA. A new class called 'Event' with several sub-classes have been added to represent information coming in via webhooks. Currently none of them are implemented, but they will be used in later work. 
We'll be skipping the wiki update for now since this currently has no impact on the code base.
=> Event Rework

locales/en.json
Adds the news moves for the 3rd gen arrive according to the Chrales datamine info
https://www.reddit.com/r/pokemongodev/comments/7i1n1j/0851_datamine/
Add the new move so that PA is ready for when the third gen of pokemon
=> Add 3 gen moves

filters.json.example
Add new raid bosses (Mawile & Absol) and add all new 3gen legendaries same as the others legendaries (1gen & 2gen)
N/A
N/A
=> Add new raid boss and prepare for 3gen legendaries

README.md
Add discord shield in readme.md
N/A
=> Add discord shield in readme

PokeAlarm/Alarms/FacebookPage/FacebookPageAlarm.py, PokeAlarm/Alarms/Slack/SlackAlarm.py
- [x ] Bug fix (non-breaking change which fixes an issue)
Fixes icon_url for Slack pokemon notifications
=> fixed default icon_url not working for slack

PokeAlarm/Events/MonEvent.py, PokeAlarm/Filters/BaseFilter.py, tests/filters/test_monster_filter.py, tests/filters/test_stop_filter.py
Unit tests for Mons and Stops! 🎉 
Make stuff easier to test for easy-to-catch bugs and faster for devs
Locally on Windows 10
=> Mon & Stop Unit Tests

tests/filters/test_monster_filter.py, tests/filters/test_raid_filter.py
Add missed CP filter test
Gotta test Mon CP
Locally on Windows 10
=> Add CP mon filter test

PokeAlarm/Alarms/Telegram/TelegramAlarm.py
=> Correct TelegramAlarm.py to egg_lvl

PokeAlarm/Alarms/Telegram/TelegramAlarm.py
=> Fix issue with Telegram egg notifications.

PokeAlarm/Alarms/Discord/DiscordAlarm.py, PokeAlarm/Alarms/FacebookPage/FacebookPageAlarm.py, PokeAlarm/Alarms/Pushbullet/PushBulletAlarm.py, PokeAlarm/Alarms/Slack/SlackAlarm.py, PokeAlarm/Alarms/Twilio/TwilioAlarm.py, PokeAlarm/Alarms/Twitter/TwitterAlarm.py
Fixed some incorrect DTS and a little unifing of default messages of PA.
Fixes
n/a
n/a
=> Fix default messages of the services

filters.json.example
With the update to the new version some things were forgotten along the way, including adding examples of min_slots / max_slots DTS.
I already added the information of these DTS in the wiki when I did the 2nd revision of the wiki.
Fixes
n/a
n/a
=> Add missed DTS min_slots/max_slots in filters example

PokeAlarm/Manager.py
Noticed that `<direction>` DTS always resulted in a `?`. Found `get_cardinal_dir` in utils and references in the *Filter.py files that cardinal directions should be handled by Manager. However, it didn't even import `get_cardinal_dir`. It was all there pre-3.5, so I tried to restore it.
I'm still a beginner in Python, so I'd be glad if you could point out any and all mistakes I made in creating this PR. Thanks :)
Restoring functionality to the `<direction>` DTS 
bug fix
Tested on a test instance with Pokemon events from webhook_test.py
=> Fix cardinal directions

data/move_info.json
Add missed info of 3 gen move stats
Fix bugs and missed info
n/a
=> Add missed stats of 3gen moves

PokeAlarm/Alarms/FacebookPage/FacebookPageAlarm.py, PokeAlarm/Alarms/Twilio/TwilioAlarm.py
=> minor corrections of comments

PokeAlarm/Filters/EggFilter.py, PokeAlarm/Filters/GymFilter.py, PokeAlarm/Filters/RaidFilter.py, PokeAlarm/Utilities/GymUtils.py
This will change "gym_name_contains" to ignore case, making it easier for users to filter on this name.
=> Change "gym_name_contains" to ignore case. 

filters.json.example
Add weather example in filters.
Fix missed info
n/a
=> Add missed weather in filters example

locales/es.json
Add translation in spanish for the new weather function in PA
Translate strings in english to spanish
n/a
=> Add weather translation in locale es

PokeAlarm/Alarms/Discord/DiscordAlarm.py, PokeAlarm/Alarms/FacebookPage/FacebookPageAlarm.py, PokeAlarm/Alarms/Pushbullet/PushBulletAlarm.py, PokeAlarm/Alarms/Slack/SlackAlarm.py, PokeAlarm/Alarms/Twilio/TwilioAlarm.py, PokeAlarm/Alarms/Twitter/TwitterAlarm.py, PokeAlarm/Geofence.py, PokeAlarm/Load.py, PokeAlarm/Manager.py, alarms.json.example, config/config.ini.example, filters.json.example, start_pokealarm.py
The "Rules" feature will allow users to create rules that dictate which filters trigger which alarms. Rules are loaded via a file containing a json object, which has 5 sections similar to the Filters file. Each section is a key-value pair of "rule names" to "rules". Each rule can be described as a json object containing just two fields: "filters" and "alarms". Each fields is an array of strings corresponding to the name of a filter or alarm from a manager. Rules cannot be created if they do not match an existing filter or alarm.
Rules are evaluated by checking listed filters one by one (in order), until a match is found. Once a match is found, PA will them notify each alarm listed in the Rule. Every rule is always evaluated every time. 
Rules is an optional configuration option. If no …
=> Rules Feature

alarms.json.example, filters.json.example
Fix missed two dots in alarms examples and remove whitespaces and fixed one section that was not closed correctly in filters (filter_by_lvl_example in the eggs example)
Fixes
n/a
n/a
=> Fix typos in examples

locales/es.json
Unified the translation of the weather into spanish with the official translation made in the game.
Unify translation in the PA with the official game translation.
n/a
=> Fix weather in es locale

tools/convert_alarms_file.py
This adds a tool which allows the conversion from the v3.5 format into the v3.6 format. Telegram users will want to verify their settings, as it only replaces keys and doesn't change the settings themselves.
=> Conversion tool for 3.5 to 3.6 alarms.

start_pokealarm.py
Makes the script run without change inside python virtualenv.
=> Update shebang line to work with virtualenv

PokeAlarm/Alarms/Twitter/__init__.py
Fix lazy loading for Twitter API
Gotta fix it
None
=> Fix Lazy Load for Twitter

docs/configuration/alarms/Discord.md, docs/configuration/alarms/index.rst
=> Test fix table and index

filters.json.example, rules.json.example
Fix error in line 8 of filters.example and unify rules file without blank spaces
Fixes
Tested
n/a
=> Fix filters.example

PokeAlarm/Events/StopEvent.py
Fixes stops not being in the correct timezone
Things relating to time weren't in the correct timezone
with guy with the bug (and it's kind of obvious that it's broke based off code)
=> Bug Fix: Timezone Incorrect on Stops

PokeAlarm/Events/MonEvent.py, PokeAlarm/Events/RaidEvent.py, PokeAlarm/Filters/MonFilter.py, PokeAlarm/Filters/RaidFilter.py, PokeAlarm/Utils.py, data/move_info.json
Adds support for Move Types to the move data files.  Also adds in Move Type DTS fields. 
The following DTS fields have been added to both **Monster** and **Raid** alerts
| DTS              | Description                                             |
|----------------- |-------------------------------------------------------- |
| quick_type_id | The id of the Quick Move's Type or  `?`.          |
| quick_type     | The name of the Quick Move's Type or `Unknown`.        |
| quick_type_emoji            | The emoji for the Quick Move's Type or Empty.        |
| charge_type_id | The id of the Charge Move's Type or  `?`.          |
| charge_type     | The name of the Charge Move's Type or `Unknown`.        |
| charge_type_emoji            | The emoji for the Charge Move's Type or Empty.        | …
=> Move Types

PokeAlarm/Events/MonEvent.py, docs/dts/monster-dts.md
This PR is adding catch prob DTS and rating attack-defense DTS.
Since some forks are sending catch probs and movesets rating, it can be usefull to add it on stock PA
Tested on my map lab, on sloppy fork
<a href="https://imgbb.com/"><img src="https://image.ibb.co/hY0kQx/github_PA.png" alt="github_PA" border="0"></a>
=> Adding catch prob and rating attack-defense DTS

docs/guides/bug-feedback.md, docs/guides/getting-started-guide.md, docs/guides/json-formatting.md, docs/guides/upgrade-tool.md, docs/index.rst
Add guides section in wiki
Some files in this section are incomplete
=> add guides section in wiki

tools/webhook_test.py
Big list o' changes:
Fix gym cache
Start using en locale file for all things data
Rework forms to allow for all mons with forms
Raids can now have different gym ids (whoopsie!)
Add team id check
Add ability to test for is_missing_info in mons (#617 )
Add raid level check
Small text formatting changes
Need cool additions, need bugs fixed
Locally -- Windows 10
=> [Bugfix & Feature Request(s)] Webhook Tester Update

docs/miscellaneous/patch-notes.md
Patch Notes for the 3.7 Release
=> 3.7 Patch Notes

PokeAlarm/Events/MonEvent.py, docs/configuration/events/monster-events.rst
Add more DTS options for catch prob, as with Height, Weight and IVs
=> Dev: catch prob dts to match IVs

docs/miscellaneous/patch-notes.md
=> Fixing DTS change for GMAPs for Patch Notes

locales/de.json
Your German rarity translation was actually Dutch lol, this will fix that.
=> Fix German translation
