alarms.json.default, alarms/__init__.py, alarms/alarm_manager.py, alarms/utils.py
Allows users to set the -sl flag to skip lured pokemon. This is useful because lured pokemon often spawn far distances from the user's search area, or have very short times. Some users would like the ability to skip notifications for them.
Made code changes and ran webhook for two days, monitoring output and logging. No errors, when flag was set, pokemon that were lured were not notified for. When flag was absent, lured pokemon were notified as intended.
Tested running with latest develop on PokemonGo-Map/PokemonGo-Map on a linux platform. Tested for 2 days.
Change falls inline with current code, also updates small parts of the code to fall in line with the rest of the code style of the project
=> Add ability to filter notifications from lured Pokestops

alarms/Twitter/twitter_alarm.py
Add optional setting `startup_message` for Twitter module.
Default on "True".
If set to "False", it prevent the Alarm from tweeting "PokeAlarm has intialized!" at startup
With my twitter, 2 times and it work.
Add to the optionnal options something like : 
```
`startup_message` | `Trigger a tweet at initialization` | `True`
```
=> [Enhancement] Add switch to disable first tweet at initialization

README.md, alarms/__init__.py, alarms/alarm_manager.py, alarms/utils.py
Added an option `-cn` or `--config` to the CLI that allows a different configuration file to be specified.  This is useful for people that to run multiple instances of PokeAlarm with different configuration files.  This is inspired from https://github.com/PokemonGoMap/PokemonGo-Map/pull/912.  If not config file is provided, the default alarms.json is used.
Tested running locally with specifying a file and then running without specifying.
README.txt was updated.  I can update the wiki as well if needed.
=> Specify a different config file on the CLI

alarms/geofence.py, alarms/utils.py, runwebhook.py
Add a simple ability to get a map of the current geofence and location.
Tested on y Ubuntu 16.04 install
Tried several different command line switches
API (section)
http://ip_address:port/geofence/ - Returns a static google map of the current location and geofence
=> Add read only Geofence/Location API map

.gitignore
I have several alarms-*.json files and .bat files in my PokeAlarm directory to quickly launch different setups. These files should not be committed to Git.
Git doesn't see these files any more. ;)
=> Git ignore all user configuration and startup scripts

alarms/utils.py, requirements.txt
This adds a new CLI option, -tz or --timezone, that sends notifications in that timezone instead of always using UTC formatted dates.  If an option isn't specified, it defaults to "UTC".  A list of valid timezone strings are available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones.
One related minor changes is adding seconds to time_12 to be consistent with time_24.
Tested specifying a timezone and tested again without.
python runwebhook.py -H 0.0.0.0 -P 4002 --config alarms.TAMARACK.json -k "XXXX" -tz "America/Los_Angeles"
- [] I have updated the documentation accordingly.
=> Support sending notifications in a specified timezone.

alarms/alarm_manager.py, alarms/utils.py
It'll enable third party tools to optionally include a new field named addinfo in the webhook request. That field brings support for all different spawn point types, 2x15,1x60h2,1x60h3 and 1x60h23.
An example: Say a 2x15 point is scanned right at the start, so without this pull request, you can either give an alarm for an expire time of 15 min, or 45 min. In reality the pokemon will stay for 15 min, hide for 15 min and then be back for 15 min, which would be a very useful information for the people receiving the alert, but it's not possible right now.
This pull request changes that.
Tested with PGO-mapscan-opt
If you integrate it, I can make a short wiki page.
=> support for different spawnpoint types

Dockerfile
Fixed `--host` variable for Docker containers
A service in docker cannot run on 127.0.0.1 and expect to have network connectivity.
In Docker?
No need to edit wiki, it's a bugfix.
=> Docker needs to run on all interfaces

locales/de/teams.json
The German translations of the team names are wrong. They look like they've been translated via google translator. I replaced them with the correct names.
not needed
not needed
=> Fix German translations of team names

PokeAlarm/Manager.py, PokeAlarm/Utils.py, locales/base_stats.json
Add size filter for pokemon, so we can also filter to find tiny rattat or big magikarps
Tested on my own map
=> Add size filter

PokeAlarm/Utils.py, PokeAlarm/WebhookStructs.py
open/create a pin in apple maps.  This allows you to use your apple watch easily to
navigate to the pokemon while still keeping open the Pokemon Go App.
There now exists <applemaps> (i.e. just like <gmaps>) to allow for text
replacement.
I use it daily.  And the twitter I have set up uses it also
- [X ] New feature (non-breaking change which adds functionality)
On this page  https://github.com/kvangent/PokeAlarm/wiki/Dynamic-Text-Substitution
add: 
<applemaps>	Apple Maps URL to pokemon location
- [ x ] My code follows the code style of this project.
=> Added the ability to have an apple maps formated url that will

PokeAlarm/Filters.py, PokeAlarm/Manager.py, PokeAlarm/Utils.py, filters.json.example
Adds the ability to filter on pokemon gender. See issue #356
Syntax example:
"Charmeleon":{ "min_iv":"100" , "gender":["male","female","neutral"] },
Run for 24 hours on my server, posting alerts filtered on IV plus male/female to Discord channels.
See: https://github.com/kvangent/PokeAlarmWiki/pull/46
=> Add filter by gender

PokeAlarm/Utils.py
With the current event lures last for 6 hours and RM has a lure_duration config command to extend the time.  However, PA reports the time as 59m 59s.  This fixes so that if time_left is over an hour it reports xh ym so that lure times can be accurate
Yes
Old:
New:
=> lure time bugfix

PokeAlarm/Discord/DiscordAlarm.py, PokeAlarm/FacebookPage/FacebookPageAlarm.py, PokeAlarm/Slack/SlackAlarm.py
Update the default URIs of raid icons to the master branch
Tested locally 
Not applicable 
- [X ] My code follows the code style of this project.
=> Update URI of raid icons to point to master

PokeAlarm/Manager.py
WIP 
Adds support for gym details in DTS for raid and eggs
* `<gym_name>`
* `<gym_description>`
* `<gym_url>`
Requires RM to scan gym details and send it
Tested locally
Will update DTS page with gym info for eggs and raids
=> Add support for gym DTS into egg and raid alarms

PokeAlarm/Manager.py
Add raid team name to raid alerts.
This gives more information on the current team controlling the raid. This information is useful because premiere balls are given based on the team controlling the raid. Gym team information is also extracted and saved earlier if gym notifications have been disabled.
This has been tested in a production environment with Discord notifications.
=> add team name to raid alert

PokeAlarm/LocationServices.py
Address DTS has been changed a tiny bit. It now will return an empty value if street name or street number is unknown. This allows for streets that have no numbers (like squares) to show up correctly. 
Example: A pokemon in a "Awesome Square, Europe City" would show up as "Awesome Square ???, Europe" it will now show up correctly with no street number.
Likewise unnamed roads wont show up as "unknown" but simply an empty string (there are many such roads in my area)
Lastly, and most importantly: there's a new DTS called `<address_eu>` that will write out "Alphabet Street 123" as addresses is usually written in Europe/Most of the world(?)
Two reasons: 
- Addresses in the EU is not written like in the US where street numbers come first. I would make the default address DTS EU style, but for …
=> Add new DTS for correct (EU) address formatting

PokeAlarm/WebhookStructs.py
Resolves AttributeError: 'float' object has no attribute '5f' in `WebhookStructs.py` due to a bad format syntax
Bugfixing is always welcome
Running locally.
=> Fix bad format syntax

PokeAlarm/Manager.py
In my opinion a cached egg webhook data should expire when the raid starts, not when it ends.
I <3 being correct!
Local map.
=> Eggs expire when the raid starts, not when it ends

PokeAlarm/Cache/Cache.py, PokeAlarm/Cache/FileCache.py, PokeAlarm/Manager.py
...plus some typos and a smaller clean_hist function
The `FileCache` wasn't getting cleaned. Only the data got stored which led to notifications not being sent.
The commit also corrects some typos in `FileCache.py` and replaces the clean_hist double-loop with a single loop according to https://stackoverflow.com/a/5385075/2787955
Bugfixing
My local map
=> Fix FileCache not getting cleaned

PokeAlarm/Twilio/TwilioAlarm.py
This PR adds support for sending alerts to multiple numbers via a Twilio.  This works by replacing the  `to_number` field of the alarm setting with an array of numbers.  
This was a requested feature under https://github.com/PokeAlarm/PokeAlarm/issues/452.  The feature gives the ability to subscribe multiple recipients for PokeAlarm alerts through Twilio. 
This was tested through my trial Twilio account using both a single number destination and an array of up to 3 individual numbers.  Tests were performed using the webhook_test utility. 
N/A
The wiki will need to be updated to indicate the changes to use the alert appropriately.
=> Twilio Multi "To_Number" Support

PokeAlarm/WebhookStructs.py
Fixes issues with Magikarp being mislabed as "Big" and Ratatta being mislabeled as "Tiny" for the associated medals.
Fixes #429 
Currently the way we check to see if big Magikarp and tiny Ratatta are big or tiny is by generic size
Big > 2.5
XS < 1.5
As it turns out this isn't correct, and based off research, the "bigness" or "smallness" isn't determined by height in the slightest, but by weight only.
Poorly. (Have no level 30s to test with)
Nerp
=> Big Magikarp / Tiny Ratatta values exact

filters.json.example
With the recent announcement on RAID Changes, Magikarp is once again a raid boss, so adding him back to the filters example file. 
**MAGIKARP IS BACK!** 
No testing needed, no functional change made. 
N/A
=> Updating  to add Magikarp back as a raid boss

PokeAlarm/Manager.py
Very simple addition of a DTS tag <team_leader> to other events including raids and eggs.
Wanted to get team leaders to call out raids and eggs so players would know who controls the gym. Also for potential future color embed feature.
Myself, Yes it very simple and breaks nothing
=> Adding <team_leader> DTS to raids and eggs

PokeAlarm/Events/RaidEvent.py
Charge move was mistakenly showing quick move id, quick fix here.
Wrong move was sent to discord in raid alarms
Myself
=> charge_move fix

PokeAlarm/Events/EggEvent.py, PokeAlarm/Events/RaidEvent.py, PokeAlarm/Filters/BaseFilter.py, PokeAlarm/Filters/EggFilter.py, PokeAlarm/Filters/GymFilter.py, PokeAlarm/Filters/MonFilter.py, PokeAlarm/Filters/RaidFilter.py, PokeAlarm/Filters/StopFilter.py, PokeAlarm/Utilities/GymUtils.py, PokeAlarm/Utilities/MonUtils.py, filters.json.example, tests/filters/test_egg_filter.py, tests/filters/test_gym_filter.py, tests/filters/test_raid_filter.py
Unit testing for Egg, Raid and Gym Filters.  Also fixes issue with`move_id` filter for raids. 
Testing the new filter changes
Locally using python unit testing
N/A
=> Unit testing for Eggs, Raids, Gyms

PokeAlarm/Events/GymEvent.py, PokeAlarm/Filters/GymFilter.py, tests/filters/test_gym_filter.py
Adds support for the `slots_available` data sent by RocketMap.  Also adds `<slots_available>` and `<guard_count>` DTS fields for Gym Alerts
Allows alerting on how many slots are available in a gym and how many guards it currently has.  Can be used to help teams coordinate gym attacks and defense. 
Tested locally using the webhook tester.
=> Pushing slots_available/guard_count DTS + min/max_slots Filters

PokeAlarm/Events/BaseEvent.py, PokeAlarm/Events/EggEvent.py, PokeAlarm/Events/GymEvent.py, PokeAlarm/Events/MonEvent.py, PokeAlarm/Events/RaidEvent.py, PokeAlarm/Events/StopEvent.py, PokeAlarm/Manager.py, PokeAlarm/Utils.py, requirements.txt, start_pokealarm.py
Remove multiprocessing and gipc and substitute greenlets instead. The queues in multiprocessing/gipc are process blocking which is causing unnecessary overhead from context switches. 
Thanks to @sebastienvercammen for pointing out the flaw in our setup.
=> Performance fixes. 

PokeAlarm/Events/EggEvent.py, PokeAlarm/Events/MonEvent.py, PokeAlarm/Events/RaidEvent.py
In my last PR, I added weather to PokeAlarm. There seems to exist now some confusion between what is the in-game weather, and the weather boosted condition of mons and raids. This PR should fix that.
The <weather> DTSs will now be used for the current in game weather for the location of the spawn or raid. The <boosted_weather> DTSs will be used to reflect whether the spawn or raid boss is boosted by the weather. 
The <weather> DTS will return the weather or 'unknown', and the <boosted_weather> will return the weather or 'None'.
=> Weather DTS improvements

PokeAlarm/Alarms/Twitter/TwitterAlarm.py
This address an issue with twitter truncation. First, the limit has been extended to 280 characters. Second the truncation now correctly works after DTS. Finally, it counts all urls as 23 characters (instead of just `<gmaps>`.
Please note this change includes the latest verson of dev, including the rules update. Please see here for more info on converting your alarms file: https://github.com/PokeAlarm/PokeAlarm/pull/564
=> Fix Twitter Truncation

PokeAlarm/Events/MonEvent.py, PokeAlarm/Events/RaidEvent.py
This PR fixes some issues in the weather alerts for mons and raids:
1. MonEvent - Changed back to setting boosted weather to 0. This is because if mon is not weather boosted scan sends None to webhook, so there is no way to differentiate between sent and not boosted and not sent. Having it set to ? mean all unboosted mons were posting unknown instead of 'None'.
1. There is an unnecessary comma that appends to a string, meaning later name lookups fails.
```
boosted_weather_id = \
0 if Unknown.is_not(self.weather_id) else Unknown.TINY,
```
The comma at the end was causing issues. I have also tidied up the code to make it similar to MonEvent
=> Weather Fixes

PokeAlarm/Manager.py
if your alarm DTS only contains address_eu , geocode lookup won't happen and the alarm will become <address_eu>
It makes alarms great again also in parts of the world that likes to write `street streetnumber`
=> bugfix: If the only address DTS you use is `<address_eu>` reverse geocode fails

PokeAlarm/Filters/BaseFilter.py, PokeAlarm/Filters/EggFilter.py, PokeAlarm/Filters/GymFilter.py, PokeAlarm/Filters/MonFilter.py, PokeAlarm/Filters/RaidFilter.py, PokeAlarm/Filters/StopFilter.py
This fix is for https://github.com/PokeAlarm/PokeAlarm/issues/601 and corrects filter geofences to be checked in order specified in the filter.
=> Fix Geofence ordering in Filters. 

PokeAlarm/Cache/Cache.py, PokeAlarm/Cache/FileCache.py, PokeAlarm/Events/EggEvent.py, PokeAlarm/Events/RaidEvent.py, PokeAlarm/Manager.py, cache/.gitignore
This is a bunch of miscellaneous cache improvements.
* Updated API to be more condensed
* Separated gym_info into gym_name, gym_desc, and gym_url into separate endpoints
* Added support for `team_id` from RM egg and raid webhooks
* FileCache now creates the cache folder upon initialization if it doesn't exist
* FileCache saves initial file with the ".new" extension and then renames over the original file to reduce the chance of the cache being corrupted if PA is closed incorrectly
* If FileCache fails to load the file for any reason, it will continue on as normal and overwrite it the cache on the next opportunity
=> Caching Improvements

data/base_stats.json, data/move_info.json
Reformatting the Move & Monster IDs with Zero Padding for proper sorting
Cleans up the data files
Tested on my production environment
=> Data File Refresh

PokeAlarm/Filters/EggFilter.py, PokeAlarm/Filters/GymFilter.py, PokeAlarm/Filters/RaidFilter.py, PokeAlarm/Utilities/GymUtils.py, tests/filters/test_egg_filter.py, tests/filters/test_gym_filter.py, tests/filters/test_raid_filter.py
This adds in a new filter to Gym, Egg and Raid Events that is the exact opposite of the current `gym_name_contains` filter. 
Allows for using regex patterns to filter out events where the `gym_name` matches one of the given patterns resulting in a rejected event. 
This was requested via #585 
This was locally tested and has functional unit tests
=> Adds gym_name_excludes filter to Gym, Egg, Raid Events

PokeAlarm/Alarms/Telegram/TelegramAlarm.py
#595 requested that the `disable_web_page_preview` option in the Telegram API be brought back
It makes sense for it to be configurable
Options
Locally on Windows 10
=> Telegram Web Preview Option

PokeAlarm/Filters/RaidFilter.py
This corrects a bug with RaidFilter that causes a parsing error at startup. 
Fixes a bug that stops PA from loading if using Raid Filters
Tested on my production environment
=> Fixed is_sponsor filter for Raids

PokeAlarm/Events/MonEvent.py, docs/configuration/events/monster-events.rst
Add addtional weight & height DTSs matching IV style, with 0,1 & 2 decimals
=> Dev Add new DTSs for Height and Weight
